1. Imports

to run 'python -m scripts.download_data' in terminal first before running this ! (improve pipeline later on) purchases csv too big,, takes too long to add and commit,,

In [9]:
import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", None)

PROJECT_ROOT = Path.cwd().parent
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw" / "x5"

print(f"Reading data from: {RAW_DATA_DIR}")

Reading data from: c:\Users\szepi\OneDrive\Documents\dse4101\DSE4101-CausalForest-Grp2\data\raw\x5

2. Load Files

In [10]:
clients = pd.read_csv(RAW_DATA_DIR / "clients.csv.gz")
#load a bit of purchases data to see headers etc,,, else takes too long to load LOL
purchases = pd.read_csv(RAW_DATA_DIR / "purchases.csv.gz", nrows = 10000)
train = pd.read_csv(RAW_DATA_DIR / "uplift_train.csv.gz")

3. Headers

In [11]:
print("CLIENTS")
print(clients.columns.tolist())
display(clients.head())

print("\nPURCHASES")
print(purchases.columns.tolist())
display(purchases.head())

print("\nTRAIN")
print(train.columns.tolist())
display(train.head())

CLIENTS
['client_id', 'first_issue_date', 'first_redeem_date', 'age', 'gender']

    client_id     first_issue_date    first_redeem_date  age gender
0  000012768d  2017-08-05 15:40:48  2018-01-04 19:30:07   45      U
1  000036f903  2017-04-10 13:54:23  2017-04-23 12:37:56   72      F
2  000048b7a6  2018-12-15 13:33:11                  NaN   68      F
3  000073194a  2017-05-23 12:56:14  2017-11-24 11:18:01   60      F
4  00007c7133  2017-05-22 16:17:08  2018-12-31 17:17:33   67      U

PURCHASES
['client_id', 'transaction_id', 'transaction_datetime', 'regular_points_received', 'express_points_received', 'regular_points_spent', 'express_points_spent', 'purchase_sum', 'store_id', 'product_id', 'product_quantity', 'trn_sum_from_iss', 'trn_sum_from_red']

,client_id,transaction_id,transaction_datetime,regular_points_received,express_points_received,regular_points_spent,express_points_spent,purchase_sum,store_id,product_id,product_quantity,trn_sum_from_iss,trn_sum_from_red
0,000012768d,7e3e2e3984,2018-12-01 07:12:45,10.0,0.0,0.0,0.0,1007.0,54a4a11a29,9a80204f78,2.0,80.0,NaN
1,000012768d,7e3e2e3984,2018-12-01 07:12:45,10.0,0.0,0.0,0.0,1007.0,54a4a11a29,da89ebd374,1.0,65.0,NaN
2,000012768d,7e3e2e3984,2018-12-01 07:12:45,10.0,0.0,0.0,0.0,1007.0,54a4a11a29,0a95e1151d,1.0,24.0,NaN
3,000012768d,7e3e2e3984,2018-12-01 07:12:45,10.0,0.0,0.0,0.0,1007.0,54a4a11a29,4055b15e4a,2.0,50.0,NaN
4,000012768d,7e3e2e3984,2018-12-01 07:12:45,10.0,0.0,0.0,0.0,1007.0,54a4a11a29,a685f1916b,1.0,22.0,NaN

TRAIN
['client_id', 'treatment_flg', 'target']

    client_id  treatment_flg  target
0  000012768d              0       1
1  000036f903              1       1
2  00010925a5              1       1
3  0001f552b0              1       1
4  00020e7b18              1       1